name: Testflight dist

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:

    - name: Environment variables
      run: set

    - name: Installed apps
      run: ls -al /Applications

    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - uses: actions/cache@v2
      name: Restore Carthage cache
      id: restore-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-

    - name: Install dependencies with Carthage
      run: carthage bootstrap --platform iOS --no-use-binaries --cache-builds
